stages:
  - dep
  - test
  - deploy

dep:
  image: node:alpine
  stage: dep
  script:
    - npm install
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 hour
    paths:
      - node_modules/

test:
  image: node:alpine
  stage: test
  script:
    - npm run test -- --coverage
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

lint:
  image: node:alpine
  stage: test
  script:
    - npm run lint

pages:
  image: node:alpine
  stage: deploy
  script:
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public/
  only:
    - master

