stages:
  - deploy

pages:
  image: node:alpine
  stage: deploy
  variables:
    GENERATE_SOURCEMAP: "false"
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules/
  artifacts:
    paths:
      - public/
  only:
    refs:
      - master
    changes:
      - canis-fe/**/*
