stages:
  - dep
  - deploy

dep:
  image: node:alpine
  stage: dep
  script:
    - npm install
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 hour
    paths:
      - node_modules/
  only:
    - master

pages:
  image: node:alpine
  stage: deploy
  script:
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public/
  only:
    - master

